# https://docs.microsoft.com/azure/devops/pipelines/languages/android
pool:
  vmImage: 'macOS-10.13'

steps:
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'assembleRelease'

- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true # Optional
    apksignerKeystoreFile: 'my.keystore'# Required when apksign == True
    apksignerKeystorePassword: 'qwerty'# Optional
    apksignerKeystoreAlias: 'my'# Optional
    apksignerKeyPassword: 'qwerty'# Optional
    #apksignerArguments: '--verbose' # Optional
    #apksignerFile: # Optional
    zipalign: false # Optional
    #zipalignFile: # Optional
- task: CopyFiles@2
  inputs:
    contents: '**/*.apk'
    targetFolder: '$(build.artifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(build.artifactStagingDirectory)'
    artifactName: 'drop'
    artifactType: 'container'

    # App Center Distribute
# Distribute app builds to testers and users via App Center
- task: AppCenterDistribute@1
  inputs:
    serverEndpoint: 'VSAP'
    appSlug: 'https://appcenter.ms/users/jeyaprakash.chinaraj/apps/kotlinfirst'
    appFile: '$(System.DefaultWorkingDirectory)/ Kotlinfirst App/drop/app/build/outputs/apk/debug/app-debug.apk'
    #symbolsOption: 'Apple' # Optional. Options: apple
    #symbolsPath: # Optional
    #symbolsPdbFiles: '**/*.pdb' # Optional
    #symbolsDsymFiles: # Optional
    #symbolsMappingTxtFile: # Optional
    #symbolsIncludeParentDirectory: # Optional
    #releaseNotesOption: 'input' # Options: input, file
    #releaseNotesInput: # Required when releaseNotesOption == Input
    #releaseNotesFile: # Required when releaseNotesOption == File
    #isMandatory: false # Optional
    #distributionGroupId: # Optional